#define FG_BLACK                   "\x1B[30m"
#define FG_RED                     "\x1B[31m"
#define FG_GREEN                   "\x1B[32m"
#define FG_YELLOW                  "\x1B[33m"
#define FG_BLUE                    "\x1B[34m"
#define FG_MAGENTA                 "\x1B[35m"
#define FG_CYAN                    "\x1B[36m"
#define FG_WHITE                   "\x1B[37m"
#define FG_GRAY                    "\x1B[90m"

#define FG_GRAY_LIGHT              "\x1B[37m"
#define FG_RED_LIGHT               "\x1B[91m"
#define FG_GREEN_LIGHT             "\x1B[92m"
#define FG_YELLOW_LIGHT            "\x1B[93m"
#define FG_BLUE_LIGHT              "\x1B[94m"
#define FG_MAGENTA_LIGHT           "\x1B[95m"
#define FG_CYAN_LIGHT              "\x1B[96m"

#define BG_BLACK                   "\x1B[40m"
#define BG_RED                     "\x1B[41m"
#define BG_GREEN                   "\x1B[42m"
#define BG_YELLOW                  "\x1B[43m"
#define BG_BLUE                    "\x1B[44m"
#define BG_MAGENTA                 "\x1B[45m"
#define BG_CYAN                    "\x1B[46m"
#define BG_WHITE                   "\x1B[47m"
#define BG_GRAY                    "\x1B[100m"

#define BG_GRAY_LIGHT              "\x1B[47m"
#define BG_RED_LIGHT               "\x1B[101m"
#define BG_GREEN_LIGHT             "\x1B[102m"
#define BG_YELLOW_LIGHT            "\x1B[103m"
#define BG_BLUE_LIGHT              "\x1B[104m"
#define BG_MAGENTA_LIGHT           "\x1B[105m"
#define BG_CYAN_LIGHT              "\x1B[106m"

#define FG_BG_CLEAR                "\x1B[0m"